version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: .docker/local/go/Dockerfile
    container_name: "go-app-api-server"
    stdin_open: true
    tty: true
    ports:
      - "8081:8081"
    volumes:
      - "./:/app"

  mysql:
    container_name: go-mysql
    build:
      context: .
      dockerfile: ".docker/local/mysql/Dockerfile"
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - ".docker/local/mysql/my.cnf:/etc/mysql/my.cnf"
      - ".mysql:/var/lib/mysql"