name: Manual
on:
  workflow_dispatch: # 手動実行イベント
    inputs:
      greeting:
        type: string
        default: "auto_assign"
        required: true
        description: A cheerful word

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"